spring.application.name=auth

# Server
server.port=8080

# Database
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/skinmate
spring.datasource.username=root
spring.datasource.password=zxczxc

# JPA 설정
# Hibernate 자동 DDL 생성 비활성화
spring.jpa.hibernate.ddl-auto=update
# MySQL8 방언 지정
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# SQL 로그 포맷팅
spring.jpa.properties.hibernate.format_sql=true
# SQL 쿼리 출력
spring.jpa.show-sql=true